spring.application.name=gestion-gastos

# BBDD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.banner-mode=off

# LOGS
logging.file.name=logs/gestion-gastos.log
logging.level.root=INFO
logging.level.com.nexzus.gestiongastos=DEBUG

# JWT
jwt.secret=8e2a0207990dd527adbff0b632fb682e58ea0af1d61d121b6df86379aca42cf7
jwt.accessTokenExpirationMs=3600000
jwt.refreshTokenExpirationMs=86400000

# GOOGLE
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}